# Generated by Django 5.2.7 on 2025-11-26 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=50)),
                ('document_file', models.FileField(upload_to='manuals/')),
                ('status', models.CharField(choices=[('current', 'Current'), ('old', 'Old')], default='current', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Manual Document',
                'verbose_name_plural': 'Manual Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('engineering', 'Engineering'), ('npd', 'NPD'), ('forging', 'Forging'), ('tool_room', 'Tool Room'), ('machining_division', 'Machining Division'), ('metallurgy_ht', 'Metallurgy & HT'), ('maintenance', 'Maintenance'), ('purchase', 'Purchase'), ('store_dispatch', 'Store and Dispatch'), ('qa', 'QA'), ('hr', 'HR'), ('mr', 'MR'), ('sales_marketing', 'Sales and Marketing')], max_length=50)),
                ('document_file', models.FileField(upload_to='procedures/')),
                ('status', models.CharField(choices=[('current', 'Current'), ('old', 'Old')], default='current', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Procedure Document',
                'verbose_name_plural': 'Procedure Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
