# Generated by Django 5.2.7 on 2025-11-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('component', models.CharField(max_length=100)),
                ('pices', models.IntegerField()),
                ('invoiceno', models.CharField(max_length=100)),
                ('addpdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('heat_no', models.CharField(max_length=100)),
                ('target1', models.IntegerField(default=0)),
                ('total_produced', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('batch_number', models.CharField(max_length=50)),
                ('verified_by', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
            ],
        ),
    ]
