# Generated by Django 5.2.7 on 2025-11-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('machine', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('verified_by', models.CharField(max_length=100)),
                ('heat_no', models.CharField(max_length=100)),
                ('target', models.IntegerField()),
                ('total_produced', models.IntegerField()),
                ('remaining', models.IntegerField(default=0)),
            ],
        ),
    ]
