# Generated by Django 5.2.7 on 2025-11-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_area_inventory', '0001_initial'),
        ('raw_material', '0012_spcdimension_spcrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_material.holdmaterial'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
