# Generated by Django 5.2.7 on 2025-11-04 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('component', models.CharField(db_index=True, max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('standerd', models.CharField(max_length=100)),
                ('heatno', models.CharField(max_length=50)),
                ('dia', models.CharField(max_length=100)),
                ('rack_no', models.CharField(max_length=50)),
                ('pieces', models.IntegerField()),
                ('hold_material_qty_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial Issue'), ('complete', 'Complete Issue')], default='open', max_length=20)),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RMReceiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('supplier', models.CharField(db_index=True, max_length=100)),
                ('grade', models.CharField(db_index=True, max_length=50)),
                ('dia', models.CharField(db_index=True, max_length=100)),
                ('customer', models.CharField(db_index=True, max_length=100)),
                ('standerd', models.CharField(max_length=100)),
                ('heatno', models.CharField(max_length=50)),
                ('reciving_weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hold_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rack_no', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('type_of_material', models.CharField(max_length=100)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_no', models.CharField(max_length=50)),
                ('milltc', models.FileField(blank=True, null=True, upload_to='reports/MILLTC')),
                ('spectro', models.FileField(blank=True, null=True, upload_to='reports/SPECTRO')),
                ('ssb_inspection_report', models.FileField(blank=True, null=True, upload_to='reports/SSBINSPECTION')),
                ('customer_approval', models.FileField(blank=True, null=True, upload_to='reports/CUSTOMERAPPROVAL')),
                ('verified_by', models.CharField(blank=True, max_length=150)),
                ('approval_status', models.CharField(blank=True, choices=[('Under Inspection', 'Under Inspection'), ('Hold', 'Hold'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default=None, max_length=20, null=True)),
                ('comments', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial Issue'), ('complete', 'Complete Issue')], default='open', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BatchTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('customer', models.CharField(max_length=100)),
                ('standard', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('dia', models.CharField(max_length=100)),
                ('heatno', models.CharField(max_length=100)),
                ('rack_no', models.CharField(max_length=100)),
                ('issue_bar_qty', models.CharField(max_length=100)),
                ('issue_qty_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.CharField(blank=True, max_length=150)),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='raw_material.holdmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='holdmaterial',
            name='rm_receiving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds', to='raw_material.rmreceiving'),
        ),
    ]
