# Generated by Django 5.2.7 on 2025-11-04 09:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0002_holdmaterial_rmreceiving_batchtracking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('customer_location', models.CharField(blank=True, max_length=100, null=True)),
                ('drawing_rev_number', models.CharField(blank=True, max_length=100, null=True)),
                ('drawing_rev_date', models.CharField(blank=True, max_length=100, null=True)),
                ('forging_line', models.CharField(blank=True, max_length=100, null=True)),
                ('drawing_sr_number', models.IntegerField()),
                ('standerd', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('slug_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia', models.CharField(max_length=100)),
                ('ht_process', models.CharField(max_length=100)),
                ('hardness_required', models.CharField(blank=True, max_length=100, null=True)),
                ('running_status', models.CharField(blank=True, max_length=100, null=True)),
                ('packing_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('ring_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('op_10_time', models.IntegerField(blank=True, null=True)),
                ('op_10_target', models.IntegerField(blank=True, null=True)),
                ('op_20_time', models.IntegerField(blank=True, null=True)),
                ('op_20_target', models.IntegerField(blank=True, null=True)),
                ('cnc_target_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.CharField(blank=True, max_length=150, null=True)),
                ('parent_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_components', to='raw_material.masterlist')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalMasterlist',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('customer_location', models.CharField(blank=True, max_length=100, null=True)),
                ('drawing_rev_number', models.CharField(blank=True, max_length=100, null=True)),
                ('drawing_rev_date', models.CharField(blank=True, max_length=100, null=True)),
                ('forging_line', models.CharField(blank=True, max_length=100, null=True)),
                ('drawing_sr_number', models.IntegerField()),
                ('standerd', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('slug_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia', models.CharField(max_length=100)),
                ('ht_process', models.CharField(max_length=100)),
                ('hardness_required', models.CharField(blank=True, max_length=100, null=True)),
                ('running_status', models.CharField(blank=True, max_length=100, null=True)),
                ('packing_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('ring_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('op_10_time', models.IntegerField(blank=True, null=True)),
                ('op_10_target', models.IntegerField(blank=True, null=True)),
                ('op_20_time', models.IntegerField(blank=True, null=True)),
                ('op_20_target', models.IntegerField(blank=True, null=True)),
                ('cnc_target_remark', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('verified_by', models.CharField(blank=True, max_length=150, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_component', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='raw_material.masterlist')),
            ],
            options={
                'verbose_name': 'historical masterlist',
                'verbose_name_plural': 'historical masterlists',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
