# Generated by Django 5.2.7 on 2025-11-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0003_masterlist_historicalmasterlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdmaterial',
            name='slug_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
