# Generated by Django 5.2.7 on 2025-11-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0004_holdmaterial_slug_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdmaterial',
            name='rm_receiving',
            field=models.ForeignKey(
                null=True,
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='holds',
                to='raw_material.rmreceiving'
            ),
        ),
    ]
