# Generated by Django 5.2.7 on 2025-11-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0005_alter_holdmaterial_rm_receiving'),
    ]

    operations = [
        migrations.AddField(
            model_name='holdmaterial',
            name='issue_qty_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
