# Generated by Django 5.2.7 on 2025-11-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0006_holdmaterial_issue_qty_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_uid', models.CharField(editable=False, max_length=20, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.CharField(max_length=100)),
                ('current_process', models.CharField(max_length=100)),
                ('next_process', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('grade', models.CharField(max_length=50)),
                ('heat_no', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('reject', 'Reject'), ('rework', 'Rework')], default='ok', max_length=10)),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
