# Generated by Django 5.2.7 on 2025-11-06 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0007_taggeneration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdmaterial',
            name='rm_receiving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='raw_material.rmreceiving'),
        ),
    ]
