# Generated by Django 5.2.7 on 2025-11-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0008_alter_holdmaterial_rm_receiving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdmaterial',
            name='slug_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
