# Generated by Django 5.2.7 on 2025-11-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0009_alter_holdmaterial_slug_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('standerd', models.CharField(blank=True, max_length=100)),
                ('dia', models.CharField(max_length=100)),
                ('slug_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pices', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date1', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('planned', models.IntegerField(default=0)),
                ('verified_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disclosure_status', models.CharField(choices=[('none', 'No Disclosure'), ('not_received', 'Not Received by Customer'), ('not_produced', 'Not Produced'), ('delay', 'Delay in Production'), ('customer_denied', 'Customer Denied')], default='none', max_length=20)),
                ('disclosure_notes', models.TextField(blank=True)),
                ('disclosure_date', models.DateTimeField(blank=True, null=True)),
                ('disclosed_by', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['-date1'],
                'indexes': [models.Index(fields=['disclosure_status'], name='raw_materia_disclos_8c360c_idx'), models.Index(fields=['date1'], name='raw_materia_date1_5c0ec2_idx')],
            },
        ),
    ]
