# Generated by Django 5.2.7 on 2025-11-26 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0011_historicalmasterlistdocument_masterlistdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPCDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=250)),
                ('dimension', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=100)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('spc_time_period_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SPCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('cpk_value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('spc_file', models.FileField(upload_to='spc_records/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='raw_material.spcdimension')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
