# Generated by Django 5.2.7 on 2025-11-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0012_spcdimension_spcrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdmaterial',
            name='issue_qty_kg',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='holdmaterial',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rmreceiving',
            name='hold_weight_kg',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rmreceiving',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
