# Generated by Django 5.2.7 on 2025-11-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=100)),
                ('furnace', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=250)),
                ('ringweight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('production', models.IntegerField()),
                ('cycle_time', models.CharField(max_length=100)),
                ('unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heat_no', models.CharField(max_length=100)),
                ('target', models.IntegerField()),
                ('total_produced', models.IntegerField()),
                ('remaining', models.IntegerField(default=0)),
                ('hardness', models.CharField(blank=True, max_length=100)),
                ('micro', models.FileField(blank=True, null=True, upload_to='heat_treatment/micro/')),
                ('grain_size', models.FileField(blank=True, null=True, upload_to='heat_treatment/grain_size/')),
                ('verified_by', models.CharField(max_length=100)),
            ],
        ),
    ]
